### ISSUE TITLE
need a way to name zedboards and choose a particular detected device

### ISSUE THREAD

**Issue by jameyhicks** [cambridgehackers/webui#12]
Let's say name goes in name.txt and we fetch the file in zdb.js.

**Comment by jameyhicks** [comment]
Added a selector based on IP addr, but need to fetch the name still.

**Comment by myronking** [comment]
I added something like this to discover_tcp.py.   If you choose a different convention, we should update this script so it is compatible.

**Comment by jameyhicks** [comment]
That code uses /mnt/sdcard/hostname but a filename with no suffix is problematic in browsers and on OS X and Windows where they use a suffix to choose an editor to launch.

Therefore, let's use /mnt/sdcard/hostname.txt -- I'll update discover_tcp.py also.

**Comment by jameyhicks** [comment]
updated agent.py and zdb.js so that the device selector uses hostname.txt if it is available.

Still need to test with a zedboard.

**Comment by jameyhicks** [comment]
Verified that it works.
